version: "3.9"
services:
  web-client:
    container_name: xray_web-client
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./projects/web-client/Dockerfile
      args:
        remote_host: localhost
        remote_port: 4001
    environment:
      XRAY_CLIENT_REMOTE_HOST: localhost
      XRAY_CLIENT_REMOTE_PORT: 4001
    ports:
      - '4000:80'
  xray_api:
    container_name: xray_api
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./projects/server/Dockerfile
    environment:
      XRAY_HTTP_PORT: 4001
      XRAY_HTTP_HOST: 0.0.0.0
      XRAY_PGUSER: treebirg
      XRAY_PGPASSWORD:
      XRAY_PGHOST: 192.168.0.23
    ports:
      - '4001:4001'
    
