version: "3.9"
services:
  web-client:
    container_name: xray_web-client
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./projects/web-client/Dockerfile
    ports:
      - '3000:80'
  api:
    container_name: xray_api
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./projects/server/Dockerfile
    environment:
      XRAY_HTTP_PORT: 3001,
      XRAY_HTTP_HOST: 0.0.0.0
    ports:
      - '3001:3001'
    
